### PR TITLE
Bump newfold-labs/wp-module-ecommerce to 0.9.2

### PR DESCRIPTION
**Pull request by aulisius**

### CODE REVIEW

**Comment by circlecube** [comment]
This is outdated since the release today includes ecommerce 1.0.8

**Comment by aulisius** [comment]
But there's a mismatch on the versions between the UI and the PHP packages. We need to get them on the same version so as to make sure the current bugs are fixed

**Comment by circlecube** [comment]
The versions seem to match to me. Are you saying we should lock this plugin to version 0.9.2 due to the UI changes? If so we can roll back to that version here.

**Comment by circlecube** [comment]
The versions seem to match to me. Are you saying we should lock this plugin to version 0.9.2 due to the UI changes? If so we can roll back to that version here.

**Comment by aulisius** [comment]
Yes, we should pin this to 0.9.2 until the whole plugin is ready with the redesign.

**Pull request closed without merging**
