### PR TITLE
Release/2.1.0

### PR DESCRIPTION
**Pull request by circlecube**
## Proposed changes

A giant release PR to bring this plugin up to date with other brand plugins.

Note: this doesn't add the ctb, staging, or help center modules. But did add the activation module and other module updates.

## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [ ] Linting and tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by circlecube** [comment]
Looks like a few ecommerce tests fail and a few onboarding tests fail.

But a few instances of what looks like complete failure, so needs a bit more investigation.

**Comment by circlecube** [comment]
@newfold-labs/press-2 and @newfold-labs/press-4 can you look at the failing tests here and see if we can get an update to fix the tests to work in Crazy Domains context too? Odd that the same module version tests pass for Bluehost and HostGator but fail for Crazy Domains.

**Comment by circlecube** [comment]
Status update, after a few more updates on my end, I'm still seeing failing tests:

E-commerce (waiting on https://github.com/newfold-labs/wp-module-ecommerce/pull/334 should fix these):
- e-commerce Home Page - When WooCommerce is installedVerify next step "Connect a payment processor"
- e-commerce Home Page - Next StepsVerify Signup for Wordpress SEO Academy step

Onboarding :
- Colors Step Test - Check Drawer Activity : Looks like the cli command to activate the theme is failing. Is there a previous step that should be installing the theme? @newfold-labs/press-2  and ideas here?

**Comment by sangeetha-nayak** [comment]
> Status update, after a few more updates on my end, I'm still seeing failing tests:
> 
> E-commerce (waiting on [newfold-labs/wp-module-ecommerce#334](https://github.com/newfold-labs/wp-module-ecommerce/pull/334) should fix these):
> 
> * e-commerce Home Page - When WooCommerce is installedVerify next step "Connect a payment processor"
> * e-commerce Home Page - Next StepsVerify Signup for Wordpress SEO Academy step
> 
> Onboarding :
> 
> * Colors Step Test - Check Drawer Activity : Looks like the cli command to activate the theme is failing. Is there a previous step that should be installing the theme? @newfold-labs/press-2  and ideas here?

Added a fix here [PR#355](https://github.com/newfold-labs/wp-plugin-crazy-domains/pull/355)

**Review by wpalani — APPROVED** [review]

**Pull request merged**
