### PR TITLE
Release/0.1.0

### PR DESCRIPTION
**Pull request by circlecube**
Early release for plugin for testing updates and giving a link to installers.

### CODE REVIEW

**Review by wpscholar — APPROVED** [review]

**Comment by wpscholar** [comment]
@circlecube Do we want to just create a new repo that isn't connected to a fork (before this goes live)?

**Comment by circlecube** [comment]
> @circlecube Do we want to just create a new repo that isn't connected to a fork (before this goes live)?

It looks like we can get this done without making a new repo. I'll try this today: https://ralphjsmit.com/unfork-github-repo

**Comment by circlecube** [comment]
I've submitted this repo to be detached from the fork. We'll see what happens there.

**Comment by circlecube** [comment]
Nice! Looks like the detach-fork ticket has completed already.

**Pull request merged**
